name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 17 * * *'
  watch:
    types: [started]
  pull_request:
  workflow_dispatch:

#permissions:
  #contents: read

jobs:
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python:
          #- '3.6'
          #- '3.7'
          #- '3.8'
          #- '3.9'
          - '3.10'
        os:
          #- ubuntu-latest
          #- macos-latest
          - windows-latest

    steps:
      #- name: Clone repository
       # uses: actions/checkout@v3
      - name: Clone repository
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions"

      - name: Run Wget
        run: PowerShell -NoProfile -ExecutionPolicy Bypass -Command ".\test.ps1"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Print versions
        run: |
          python --version
          pip --version

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8

      - name: Run makeHosts.py
        run: python makeHosts.py

      - name: Run tests
        run: python testUpdateHostsFile.py

      - name: Run Update
        run: python updateHostsFile.py -a -e fakenews gambling social -m -x blacklist -o build

      - name: push
        run: |
          echo "======================="
          git add . && git commit -m "$(date "+%Y%m%d-%H%M")" && git push && echo "UPDATE SUCCESS!" || echo "There are currently no updates!"
          echo "======================="
        
        

